[project]
name = "learning-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flappy-bird-gymnasium>=0.4.0",
    "gymnasium>=1.2.3",
    "pygame>=2.6.1",
    "torch>=2.10.0",
]
